version: "3.9"
services:
  server:
    container_name: serverNodejs
    image: everchicas/servernodejs
    ports:
      - 3001:3001
    volumes:
      - /proc:/proc
    networks:
      - networkapi
    # links:
    #   - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    networks:
      - networkapi

volumes:
  db-data:
    driver: local

networks:
  networkapi: 
    driver: bridge