version: "3.3"
services:
  grpcserver:
    build: ./server
    ports:
      - "50051:50051"
    networks:
      - grpcapp

  grpcclient:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - grpcapp

networks:
  grpcapp:
    driver: "bridge"